name: ci

on:
  push:
    branches:
      - v1
  pull_request:
    branches:
      - v1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v4
